<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>EsoLogFilter</AssemblyName>
    <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    <RootNamespace>EsoLogFilter.Ui.Wpf</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LowFps.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="LowFps.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\core\Core.csproj" />
    <ProjectReference Include="..\infrastructure-file\Infrastructure.File.csproj" />
  </ItemGroup>

</Project>